// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hhukvpvqjsccqwvywoee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhodWt2cHZxanNjY3F3dnl3b2VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1OTAyNzUsImV4cCI6MjA3NDE2NjI3NX0.43vekofiKmqcFW1q1kjeGGQtt1UA4AyrxxsMqPHzcdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);